### ISSUE TITLE
EncryptedSession uses deprecated Flask attribute

### ISSUE THREAD

**Issue by williamjacksn** [joshuabach/gnucash-web#41]
```
[2023-05-31 01:48:57,257] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/python/venv/lib/python3.11/site-packages/flask/app.py", line 2189, in wsgi_app
    ctx.push()
  File "/home/python/venv/lib/python3.11/site-packages/flask/ctx.py", line 377, in push
    self.session = session_interface.open_session(self.app, self.request)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python/venv/lib/python3.11/site-packages/encrypted_session/__init__.py", line 33, in open_session
    session_cookie = request.cookies.get(app.session_cookie_name)
                                         ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Flask' object has no attribute 'session_cookie_name'
```

`app.session_cookie_name` was removed in Flask 2.3, so pinning Flask to <2.3 in `setup.py` is a sufficient workaround for now.

**Comment by joshuabach** [comment]
See also #35. In the mid-term, I will likely want to get rid of EncryptedSession entirely.

In the short term, pinning Flask or forking EncryptedSession is probably the best option.

Thanks for your issues by the way. Time is scarce right now, but I will crunch some issues in July.
