### ISSUE TITLE
[BUG] Compatibility with Flask >= 2.3.0

### ISSUE THREAD

**Issue by 79vette** [joshuabach/gnucash-web#49]
Hi,

When I try to access the web server at <localIP>:8080, the browser returns a 500 error and I get the following message from the uWSGI shell:

```
ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/root/.venv/lib/python3.11/site-packages/flask/app.py", line 2189, in wsgi_app
    ctx.push()
  File "/root/.venv/lib/python3.11/site-packages/flask/ctx.py", line 377, in push
    self.session = session_interface.open_session(self.app, self.request)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.11/site-packages/encrypted_session/__init__.py", line 33, in open_session
    session_cookie = request.cookies.get(app.session_cookie_name)
                                         ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Flask' object has no attribute 'session_cookie_name'
```
Looking at the version release notes for Flask, I see
```
as of 2.3.0 The session_cookie_name, send_file_max_age_default, use_x_sendfile, propagate_exceptions, and templates_auto_reload properties on app are removed.
```

Running the following to downgrade to an older Flask (pre-2.3.0) was able to resolve this.  Is this a known issue, or is there maybe something specific to my installation that is causing this error?
```
pip uninstall flask
pip install --force-reinstall flask==2.2.5
```

------------------------------------------------------------------------------------------------------------
**Long info on how I have installed and configured the app:**

when I try to install the app, `pip install gnucash-web` fails with this error message:
```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
```

Installing into a venv works, so I did that instead:
```
python3 -m venv .venv
source .venv/bin/activate
pip install GnuCash-Web
pip install uwsgi
```

I created a config file at etc/gnucash_web_config.py:
```
import logging

# A 32-bit-key used e.g. to encrypt the session cookie or for other cryptographic operations
SECRET_KEY = '<32 bit key>'

# Python standard library log level
LOG_LEVEL = logging.WARN

# Supported values: 'sqlite', 'mysql' or 'postgres'
DB_DRIVER = 'sqlite'

# Host name of the database (ignored for DB_DRIVER = 'sqlite')
DB_HOST = 'database.example.org'

# Name of the Database on the host (for DB_DRIVER = 'sqlite', this is the 'path/to/db.sqlite')
DB_NAME = '/mnt/gnucash/FY_2023.sqlite'

# Supported values: None, 'passthrough'. See below for details.
AUTH_MECHANISM = None

# The maximum number of transactions per page in the ledger
TRANSACTION_PAGE_LENGTH = 25

# Name of the account to be preselected when creating new transactions (optional)
#PRESELECTED_CONTRA_ACCOUNT = 'Example:Account'
```

Then I can start the application:
```
~# uwsgi --ini /root/.venv/bin/gnucash.ini
[uWSGI] getting INI configuration from /root/.venv/bin/gnucash.ini
*** Starting uWSGI 2.0.22 (64bit) on [Sat Sep  9 22:25:22 2023] ***
compiled with version: 12.3.0 on 09 September 2023 22:03:45
os: Linux-6.2.16-3-pve #1 SMP PREEMPT_DYNAMIC PVE 6.2.16-3 (2023-06-17T05:58Z)
nodename: gnuCash
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root
writing pidfile to gnucash_web.pid
detected binary path: /root/.venv/bin/uwsgi
your processes number limit is 189765
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8080 fd 3
Python version: 3.11.4 (main, Jun  9 2023, 07:59:55) [GCC 12.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7fdbce161018
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7fdbce161018 pid: 5887 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5887)
spawned uWSGI worker 1 (pid: 5890, cores: 1)
```

**Comment by joshuabach** [comment]
Hei 79vette, thanks for your detailed report!

Yes, this is a known issue, see #41
